# generated by datamodel-codegen

from entitysdk.compat import StrEnum


class ActivityStatus(StrEnum):
    created = "created"
    pending = "pending"
    running = "running"
    done = "done"
    error = "error"
    cancelled = "cancelled"


class ActivityType(StrEnum):
    simulation_execution = "simulation_execution"
    simulation_generation = "simulation_generation"
    validation = "validation"
    calibration = "calibration"
    analysis_notebook_execution = "analysis_notebook_execution"
    ion_channel_modeling_execution = "ion_channel_modeling_execution"
    ion_channel_modeling_config_generation = "ion_channel_modeling_config_generation"
    skeletonization_execution = "skeletonization_execution"
    skeletonization_config_generation = "skeletonization_config_generation"
    task_activity = "task_activity"


class AgePeriod(StrEnum):
    prenatal = "prenatal"
    postnatal = "postnatal"
    unknown = "unknown"


class AgentType(StrEnum):
    person = "person"
    organization = "organization"
    consortium = "consortium"


class AnalysisScale(StrEnum):
    subcellular = "subcellular"
    cellular = "cellular"
    circuit = "circuit"
    system = "system"


class ApiErrorCode(StrEnum):
    GENERIC_ERROR = "GENERIC_ERROR"
    NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
    NOT_AUTHORIZED = "NOT_AUTHORIZED"
    INVALID_REQUEST = "INVALID_REQUEST"
    ENTITY_NOT_FOUND = "ENTITY_NOT_FOUND"
    ENTITY_FORBIDDEN = "ENTITY_FORBIDDEN"
    ENTITY_DUPLICATED = "ENTITY_DUPLICATED"
    ASSET_NOT_FOUND = "ASSET_NOT_FOUND"
    ASSET_DUPLICATED = "ASSET_DUPLICATED"
    ASSET_INVALID_FILE = "ASSET_INVALID_FILE"
    ASSET_MISSING_PATH = "ASSET_MISSING_PATH"
    ASSET_INVALID_PATH = "ASSET_INVALID_PATH"
    ASSET_NOT_A_DIRECTORY = "ASSET_NOT_A_DIRECTORY"
    ASSET_INVALID_SCHEMA = "ASSET_INVALID_SCHEMA"
    ASSET_INVALID_CONTENT_TYPE = "ASSET_INVALID_CONTENT_TYPE"
    ASSET_UPLOAD_INCOMPLETE = "ASSET_UPLOAD_INCOMPLETE"
    ASSET_UPLOAD_INCONSISTENT_SIZE = "ASSET_UPLOAD_INCONSISTENT_SIZE"
    ASSET_NOT_UPLOADING = "ASSET_NOT_UPLOADING"
    ASSET_VIRTUAL_LAB_ID_NOT_FOUND = "ASSET_VIRTUAL_LAB_ID_NOT_FOUND"
    ION_NAME_NOT_FOUND = "ION_NAME_NOT_FOUND"
    S3_CANNOT_CREATE_PRESIGNED_URL = "S3_CANNOT_CREATE_PRESIGNED_URL"
    OPENAI_API_KEY_MISSING = "OPENAI_API_KEY_MISSING"
    OPENAI_API_ERROR = "OPENAI_API_ERROR"


class AssetLabel(StrEnum):
    directory_child = "directory_child"
    morphology = "morphology"
    morphology_with_spines = "morphology_with_spines"
    cell_composition_summary = "cell_composition_summary"
    cell_composition_volumes = "cell_composition_volumes"
    single_neuron_synaptome_config = "single_neuron_synaptome_config"
    single_neuron_synaptome_simulation_data = "single_neuron_synaptome_simulation_data"
    single_neuron_simulation_data = "single_neuron_simulation_data"
    sonata_circuit = "sonata_circuit"
    compressed_sonata_circuit = "compressed_sonata_circuit"
    circuit_figures = "circuit_figures"
    circuit_analysis_data = "circuit_analysis_data"
    circuit_connectivity_matrices = "circuit_connectivity_matrices"
    task_result = "task_result"
    nwb = "nwb"
    neuron_hoc = "neuron_hoc"
    electrode_locations = "electrode_locations"
    emodel_optimization_output = "emodel_optimization_output"
    emodel_optimisation_checkpoint = "emodel_optimisation_checkpoint"
    emodel_analysis_figures = "emodel_analysis_figures"
    emodel_analysis_summary = "emodel_analysis_summary"
    sonata_simulation_config = "sonata_simulation_config"
    simulation_generation_config = "simulation_generation_config"
    ion_channel_modeling_generation_config = "ion_channel_modeling_generation_config"
    custom_node_sets = "custom_node_sets"
    compartment_sets = "compartment_sets"
    campaign_generation_config = "campaign_generation_config"
    campaign_summary = "campaign_summary"
    replay_spikes = "replay_spikes"
    voltage_report = "voltage_report"
    spike_report = "spike_report"
    lfp_report = "lfp_report"
    neuron_mechanisms = "neuron_mechanisms"
    brain_atlas_annotation = "brain_atlas_annotation"
    brain_atlas_region_mesh = "brain_atlas_region_mesh"
    voxel_densities = "voxel_densities"
    validation_result_figure = "validation_result_figure"
    validation_result_details = "validation_result_details"
    simulation_designer_image = "simulation_designer_image"
    circuit_visualization = "circuit_visualization"
    node_stats = "node_stats"
    network_stats_a = "network_stats_a"
    network_stats_b = "network_stats_b"
    cell_surface_mesh = "cell_surface_mesh"
    jupyter_notebook = "jupyter_notebook"
    requirements = "requirements"
    notebook_required_files = "notebook_required_files"
    ion_channel_model_figure = "ion_channel_model_figure"
    ion_channel_model_figure_summary_json = "ion_channel_model_figure_summary_json"
    ion_channel_model_thumbnail = "ion_channel_model_thumbnail"
    circuit_extraction_config = "circuit_extraction_config"
    skeletonization_config = "skeletonization_config"
    task_config = "task_config"
    lod_mesh_block = "lod_mesh_block"
    electrode_array_weight_matrix = "electrode_array_weight_matrix"
    electrode_array_image = "electrode_array_image"
    efeature_extraction_features = "efeature_extraction_features"
    efeature_extraction_figures = "efeature_extraction_figures"
    efeature_extraction_cells = "efeature_extraction_cells"
    efeature_extraction_protocols = "efeature_extraction_protocols"
    current_report = "current_report"


class AssetStatus(StrEnum):
    created = "created"
    uploading = "uploading"


class CellMorphologyGenerationType(StrEnum):
    digital_reconstruction = "digital_reconstruction"
    modified_reconstruction = "modified_reconstruction"
    computationally_synthesized = "computationally_synthesized"
    placeholder = "placeholder"


class CellMorphologyProtocolDesign(StrEnum):
    electron_microscopy = "electron_microscopy"
    cell_patch = "cell_patch"
    fluorophore = "fluorophore"
    topological_synthesis = "topological_synthesis"


class CircuitBuildCategory(StrEnum):
    computational_model = "computational_model"
    em_reconstruction = "em_reconstruction"


class CircuitScale(StrEnum):
    single = "single"
    pair = "pair"
    small = "small"
    microcircuit = "microcircuit"
    region = "region"
    system = "system"
    whole_brain = "whole_brain"


class ContentType(StrEnum):
    application_json = "application/json"
    application_swc = "application/swc"
    application_nrrd = "application/nrrd"
    application_obj = "application/obj"
    application_hoc = "application/hoc"
    application_asc = "application/asc"
    application_abf = "application/abf"
    application_nwb = "application/nwb"
    application_x_hdf5 = "application/x-hdf5"
    text_plain = "text/plain"
    application_vnd_directory = "application/vnd.directory"
    application_mod = "application/mod"
    application_pdf = "application/pdf"
    image_png = "image/png"
    image_jpeg = "image/jpeg"
    model_gltf_binary = "model/gltf-binary"
    application_gzip = "application/gzip"
    image_webp = "image/webp"
    application_x_ipynb_json = "application/x-ipynb+json"
    application_zip = "application/zip"
    application_octet_stream = "application/octet-stream"


class DerivationType(StrEnum):
    circuit_customization = "circuit_customization"
    circuit_extraction = "circuit_extraction"
    circuit_rewiring = "circuit_rewiring"
    emodel_circuit = "emodel_circuit"
    em_dense_reconstruction_dataset_cell_morphology = (
        "em_dense_reconstruction_dataset_cell_morphology"
    )
    circuit_simplification = "circuit_simplification"
    unspecified = "unspecified"


class EMCellMeshGenerationMethod(StrEnum):
    marching_cubes = "marching_cubes"


class EMCellMeshType(StrEnum):
    static = "static"
    dynamic = "dynamic"


class ElectricalRecordingOrigin(StrEnum):
    in_vivo = "in_vivo"
    in_vitro = "in_vitro"
    in_silico = "in_silico"
    unknown = "unknown"


class ElectricalRecordingStimulusShape(StrEnum):
    cheops = "cheops"
    constant = "constant"
    pulse = "pulse"
    step = "step"
    ramp = "ramp"
    noise = "noise"
    sinusoidal = "sinusoidal"
    other = "other"
    two_steps = "two_steps"
    unknown = "unknown"


class ElectricalRecordingStimulusType(StrEnum):
    voltage_clamp = "voltage_clamp"
    current_clamp = "current_clamp"
    conductance_clamp = "conductance_clamp"
    extracellular = "extracellular"
    other = "other"
    unknown = "unknown"


class ElectricalRecordingType(StrEnum):
    intracellular = "intracellular"
    extracellular = "extracellular"
    both = "both"
    unknown = "unknown"


class ElectrodeType(StrEnum):
    neuropixels_v1 = "neuropixels_v1"
    neuropixels_v2 = "neuropixels_v2"
    neuropixels_ultra = "neuropixels_ultra"
    custom = "custom"


class EntityExpand(StrEnum):
    generated_from_derivations = "generated_from_derivations"
    used_by_derivations = "used_by_derivations"


class EntityLifecycleStatus(StrEnum):
    draft = "draft"
    active = "active"
    disqualified = "disqualified"


class EntityRoute(StrEnum):
    brain_atlas = "brain-atlas"
    brain_atlas_region = "brain-atlas-region"
    cell_composition = "cell-composition"
    cell_morphology = "cell-morphology"
    cell_morphology_protocol = "cell-morphology-protocol"
    electrical_cell_recording = "electrical-cell-recording"
    electrical_recording_stimulus = "electrical-recording-stimulus"
    emodel = "emodel"
    experimental_bouton_density = "experimental-bouton-density"
    experimental_neuron_density = "experimental-neuron-density"
    experimental_synapses_per_connection = "experimental-synapses-per-connection"
    external_url = "external-url"
    ion_channel_model = "ion-channel-model"
    ion_channel_modeling_campaign = "ion-channel-modeling-campaign"
    ion_channel_modeling_config = "ion-channel-modeling-config"
    ion_channel_recording = "ion-channel-recording"
    memodel = "memodel"
    memodel_calibration_result = "memodel-calibration-result"
    task_result = "task-result"
    simulation = "simulation"
    simulation_campaign = "simulation-campaign"
    simulation_result = "simulation-result"
    single_neuron_simulation = "single-neuron-simulation"
    single_neuron_synaptome = "single-neuron-synaptome"
    single_neuron_synaptome_simulation = "single-neuron-synaptome-simulation"
    simulatable_extracellular_recording_array = "simulatable-extracellular-recording-array"
    subject = "subject"
    validation_result = "validation-result"
    circuit = "circuit"
    em_dense_reconstruction_dataset = "em-dense-reconstruction-dataset"
    em_cell_mesh = "em-cell-mesh"
    analysis_notebook_template = "analysis-notebook-template"
    analysis_notebook_environment = "analysis-notebook-environment"
    analysis_notebook_result = "analysis-notebook-result"
    skeletonization_config = "skeletonization-config"
    skeletonization_campaign = "skeletonization-campaign"
    task_config = "task-config"


class EntityType(StrEnum):
    analysis_software_source_code = "analysis_software_source_code"
    brain_atlas = "brain_atlas"
    brain_atlas_region = "brain_atlas_region"
    cell_composition = "cell_composition"
    cell_morphology = "cell_morphology"
    cell_morphology_protocol = "cell_morphology_protocol"
    electrical_cell_recording = "electrical_cell_recording"
    electrical_recording = "electrical_recording"
    electrical_recording_stimulus = "electrical_recording_stimulus"
    emodel = "emodel"
    task_result = "task_result"
    experimental_bouton_density = "experimental_bouton_density"
    experimental_neuron_density = "experimental_neuron_density"
    experimental_synapses_per_connection = "experimental_synapses_per_connection"
    external_url = "external_url"
    ion_channel_model = "ion_channel_model"
    ion_channel_modeling_campaign = "ion_channel_modeling_campaign"
    ion_channel_modeling_config = "ion_channel_modeling_config"
    ion_channel_recording = "ion_channel_recording"
    memodel = "memodel"
    memodel_calibration_result = "memodel_calibration_result"
    me_type_density = "me_type_density"
    simulation = "simulation"
    simulation_campaign = "simulation_campaign"
    simulation_result = "simulation_result"
    scientific_artifact = "scientific_artifact"
    single_neuron_simulation = "single_neuron_simulation"
    single_neuron_synaptome = "single_neuron_synaptome"
    single_neuron_synaptome_simulation = "single_neuron_synaptome_simulation"
    simulatable_extracellular_recording_array = "simulatable_extracellular_recording_array"
    subject = "subject"
    validation_result = "validation_result"
    circuit = "circuit"
    em_dense_reconstruction_dataset = "em_dense_reconstruction_dataset"
    em_cell_mesh = "em_cell_mesh"
    analysis_notebook_template = "analysis_notebook_template"
    analysis_notebook_environment = "analysis_notebook_environment"
    analysis_notebook_result = "analysis_notebook_result"
    skeletonization_config = "skeletonization_config"
    skeletonization_campaign = "skeletonization_campaign"
    task_config = "task_config"


class EntityTypeWithBrainRegion(StrEnum):
    brain_atlas_region = "brain_atlas_region"
    cell_composition = "cell_composition"
    cell_morphology = "cell_morphology"
    circuit = "circuit"
    electrical_cell_recording = "electrical_cell_recording"
    electrical_recording = "electrical_recording"
    em_cell_mesh = "em_cell_mesh"
    em_dense_reconstruction_dataset = "em_dense_reconstruction_dataset"
    emodel = "emodel"
    experimental_bouton_density = "experimental_bouton_density"
    experimental_neuron_density = "experimental_neuron_density"
    experimental_synapses_per_connection = "experimental_synapses_per_connection"
    ion_channel_model = "ion_channel_model"
    ion_channel_recording = "ion_channel_recording"
    me_type_density = "me_type_density"
    memodel = "memodel"
    scientific_artifact = "scientific_artifact"
    single_neuron_simulation = "single_neuron_simulation"
    single_neuron_synaptome = "single_neuron_synaptome"
    single_neuron_synaptome_simulation = "single_neuron_synaptome_simulation"


class ExecutorType(StrEnum):
    single_node_job = "single_node_job"
    distributed_job = "distributed_job"
    jupyter_notebook = "jupyter_notebook"


class Expandable(StrEnum):
    measurement_annotation = "measurement_annotation"
    generated_from_derivations = "generated_from_derivations"
    used_by_derivations = "used_by_derivations"


class ExpandableAttribute(StrEnum):
    measurement_annotation = "measurement_annotation"
    generated_from_derivations = "generated_from_derivations"
    used_by_derivations = "used_by_derivations"


class ExternalSource(StrEnum):
    channelpedia = "channelpedia"
    modeldb = "modeldb"
    icgenealogy = "icgenealogy"


class MeasurableEntity(StrEnum):
    cell_morphology = "cell_morphology"
    em_cell_mesh = "em_cell_mesh"


class MeasurementStatistic(StrEnum):
    mean = "mean"
    median = "median"
    mode = "mode"
    variance = "variance"
    data_point = "data_point"
    sample_size = "sample_size"
    standard_error = "standard_error"
    standard_deviation = "standard_deviation"
    raw = "raw"
    minimum = "minimum"
    maximum = "maximum"
    sum = "sum"


class MeasurementUnit(StrEnum):
    dimensionless = "dimensionless"
    field_1_μm = "1/μm"
    field_1_μm_ = "1/μm²"
    field_1_mm_ = "1/mm³"
    μm = "μm"
    μm_ = "μm²"
    μm__1 = "μm³"
    radian = "radian"


class ModifiedMorphologyMethodType(StrEnum):
    cloned = "cloned"
    mix_and_match = "mix_and_match"
    mousified = "mousified"
    ratified = "ratified"


class PublicationType(StrEnum):
    entity_source = "entity_source"
    component_source = "component_source"
    application = "application"


class RepairPipelineType(StrEnum):
    raw = "raw"
    curated = "curated"
    unraveled = "unraveled"
    repaired = "repaired"


class Sex(StrEnum):
    male = "male"
    female = "female"
    unknown = "unknown"


class SlicingDirectionType(StrEnum):
    coronal = "coronal"
    sagittal = "sagittal"
    horizontal = "horizontal"
    custom = "custom"


class StainingType(StrEnum):
    golgi = "golgi"
    nissl = "nissl"
    luxol_fast_blue = "luxol_fast_blue"
    fluorescent_nissl = "fluorescent_nissl"
    fluorescent_dyes = "fluorescent_dyes"
    fluorescent_protein_expression = "fluorescent_protein_expression"
    immunohistochemistry = "immunohistochemistry"
    other = "other"


class StorageType(StrEnum):
    aws_s3_internal = "aws_s3_internal"
    aws_s3_open = "aws_s3_open"


class StructuralDomain(StrEnum):
    apical_dendrite = "apical_dendrite"
    basal_dendrite = "basal_dendrite"
    axon = "axon"
    soma = "soma"
    neuron_morphology = "neuron_morphology"
    not_applicable = "not_applicable"


class TargetSimulator(StrEnum):
    Brian2 = "Brian2"
    CORENEURON = "CORENEURON"
    LearningEngine = "LearningEngine"
    NEST = "NEST"
    NEURON = "NEURON"


class TaskActivityType(StrEnum):
    circuit_simulation__config_generation = "circuit_simulation__config_generation"
    circuit_simulation__execution = "circuit_simulation__execution"
    circuit_extraction__config_generation = "circuit_extraction__config_generation"
    circuit_extraction__execution = "circuit_extraction__execution"
    ion_channel_modeling__config_generation = "ion_channel_modeling__config_generation"
    ion_channel_modeling__execution = "ion_channel_modeling__execution"
    skeletonization__config_generation = "skeletonization__config_generation"
    skeletonization__execution = "skeletonization__execution"
    ion_channel_simulation__config_generation = "ion_channel_simulation__config_generation"
    ion_channel_simulation__execution = "ion_channel_simulation__execution"
    em_synapse_mapping__config_generation = "em_synapse_mapping__config_generation"
    em_synapse_mapping__execution = "em_synapse_mapping__execution"
    aind_ephys_preprocessing__config_generation = "aind_ephys_preprocessing__config_generation"
    aind_ephys_preprocessing__execution = "aind_ephys_preprocessing__execution"
    aind_ephys_spikesorting__config_generation = "aind_ephys_spikesorting__config_generation"
    aind_ephys_spikesorting__execution = "aind_ephys_spikesorting__execution"
    extracellular_recording_weights_calculation__config_generation = (
        "extracellular_recording_weights_calculation__config_generation"
    )
    extracellular_recording_weights_calculation__execution = (
        "extracellular_recording_weights_calculation__execution"
    )
    mesh_lod_generation__config_generation = "mesh_lod_generation__config_generation"
    mesh_lod_generation__execution = "mesh_lod_generation__execution"
    efeature_extraction__config_generation = "efeature_extraction__config_generation"
    efeature_extraction__execution = "efeature_extraction__execution"
    emodel_optimization__config_generation = "emodel_optimization__config_generation"
    emodel_optimization__execution = "emodel_optimization__execution"
    optimized_emodel_analysis_validation__config_generation = (
        "optimized_emodel_analysis_validation__config_generation"
    )
    optimized_emodel_analysis_validation__execution = (
        "optimized_emodel_analysis_validation__execution"
    )
    circuit_synaptic_physiology_assignment__config_generation = (
        "circuit_synaptic_physiology_assignment__config_generation"
    )
    circuit_synaptic_physiology_assignment__execution = (
        "circuit_synaptic_physiology_assignment__execution"
    )
    circuit_simplification__config_generation = "circuit_simplification__config_generation"
    circuit_simplification__execution = "circuit_simplification__execution"
    circuit_single_build__config_generation = "circuit_single_build__config_generation"
    circuit_single_build__execution = "circuit_single_build__execution"


class TaskConfigType(StrEnum):
    circuit_simulation__campaign = "circuit_simulation__campaign"
    circuit_simulation__config = "circuit_simulation__config"
    circuit_extraction__campaign = "circuit_extraction__campaign"
    circuit_extraction__config = "circuit_extraction__config"
    ion_channel_modeling__campaign = "ion_channel_modeling__campaign"
    ion_channel_modeling__config = "ion_channel_modeling__config"
    skeletonization__campaign = "skeletonization__campaign"
    skeletonization__config = "skeletonization__config"
    ion_channel_simulation__campaign = "ion_channel_simulation__campaign"
    ion_channel_simulation__config = "ion_channel_simulation__config"
    em_synapse_mapping__campaign = "em_synapse_mapping__campaign"
    em_synapse_mapping__config = "em_synapse_mapping__config"
    aind_ephys_preprocessing__campaign = "aind_ephys_preprocessing__campaign"
    aind_ephys_preprocessing__config = "aind_ephys_preprocessing__config"
    aind_ephys_spikesorting__campaign = "aind_ephys_spikesorting__campaign"
    aind_ephys_spikesorting__config = "aind_ephys_spikesorting__config"
    extracellular_recording_weights_calculation__campaign = (
        "extracellular_recording_weights_calculation__campaign"
    )
    extracellular_recording_weights_calculation__config = (
        "extracellular_recording_weights_calculation__config"
    )
    mesh_lod_generation__campaign = "mesh_lod_generation__campaign"
    mesh_lod_generation__config = "mesh_lod_generation__config"
    efeature_extraction__campaign = "efeature_extraction__campaign"
    efeature_extraction__config = "efeature_extraction__config"
    emodel_optimization__campaign = "emodel_optimization__campaign"
    emodel_optimization__config = "emodel_optimization__config"
    optimized_emodel_analysis_validation__campaign = (
        "optimized_emodel_analysis_validation__campaign"
    )
    optimized_emodel_analysis_validation__config = "optimized_emodel_analysis_validation__config"
    circuit_synaptic_physiology_assignment__campaign = (
        "circuit_synaptic_physiology_assignment__campaign"
    )
    circuit_synaptic_physiology_assignment__config = (
        "circuit_synaptic_physiology_assignment__config"
    )
    circuit_simplification__campaign = "circuit_simplification__campaign"
    circuit_simplification__config = "circuit_simplification__config"
    circuit_single_build__campaign = "circuit_single_build__campaign"
    circuit_single_build__config = "circuit_single_build__config"


class TaskResultType(StrEnum):
    circuit_simulation__result = "circuit_simulation__result"
    circuit_extraction__circuit = "circuit_extraction__circuit"
    ion_channel_modeling__result = "ion_channel_modeling__result"
    skeletonization__morphology = "skeletonization__morphology"
    ion_channel_simulation__result = "ion_channel_simulation__result"
    em_synapse_mapping__result = "em_synapse_mapping__result"
    aind_ephys_preprocessing__result = "aind_ephys_preprocessing__result"
    aind_ephys_spikesorting__result = "aind_ephys_spikesorting__result"
    extracellular_recording_weights_calculation__result = (
        "extracellular_recording_weights_calculation__result"
    )
    mesh_lod_generation__result = "mesh_lod_generation__result"
    efeature_extraction__result = "efeature_extraction__result"
    emodel_optimization__result = "emodel_optimization__result"
    optimized_emodel_analysis_validation__result = "optimized_emodel_analysis_validation__result"
    circuit_synaptic_physiology_assignment__result = (
        "circuit_synaptic_physiology_assignment__result"
    )


class ValidationStatus(StrEnum):
    created = "created"
    initialized = "initialized"
    running = "running"
    done = "done"
    error = "error"


class WithinBrainRegionDirection(StrEnum):
    ascendants = "ascendants"
    descendants = "descendants"
    ascendants_and_descendants = "ascendants_and_descendants"
