# generated by datamodel-codegen:
#   filename:  https://staging.openbraininstitute.org/api/entitycore/openapi.json
#   timestamp: 2025-06-17T16:54:49+00:00

from __future__ import annotations
from enum import Enum
from uuid import UUID
from pydantic import BaseModel, Field, PositiveFloat, RootModel, UUID4
from datetime import datetime
from typing import Any


class ActivityType(StrEnum):
    simulation_execution = "simulation_execution"
    simulation_generation = "simulation_generation"


class AgePeriod(StrEnum):
    prenatal = "prenatal"
    postnatal = "postnatal"
    unknown = "unknown"


class Annotation(BaseModel):
    id: UUID = Field(..., title="Id")
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    pref_label: str = Field(..., title="Pref Label")
    alt_label: str = Field(..., title="Alt Label")
    definition: str = Field(..., title="Definition")


class ApiErrorCode(StrEnum):
    GENERIC_ERROR = "GENERIC_ERROR"
    NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
    NOT_AUTHORIZED = "NOT_AUTHORIZED"
    INVALID_REQUEST = "INVALID_REQUEST"
    ENTITY_NOT_FOUND = "ENTITY_NOT_FOUND"
    ENTITY_FORBIDDEN = "ENTITY_FORBIDDEN"
    ENTITY_DUPLICATED = "ENTITY_DUPLICATED"
    ASSET_NOT_FOUND = "ASSET_NOT_FOUND"
    ASSET_DUPLICATED = "ASSET_DUPLICATED"
    ASSET_INVALID_FILE = "ASSET_INVALID_FILE"
    ASSET_MISSING_PATH = "ASSET_MISSING_PATH"
    ASSET_INVALID_PATH = "ASSET_INVALID_PATH"
    ASSET_NOT_A_DIRECTORY = "ASSET_NOT_A_DIRECTORY"
    ASSET_INVALID_SCHEMA = "ASSET_INVALID_SCHEMA"
    ION_NAME_NOT_FOUND = "ION_NAME_NOT_FOUND"


class AssetLabel(StrEnum):
    neurolucida = "neurolucida"
    swc = "swc"
    hdf5 = "hdf5"
    cell_composition_summary = "cell_composition_summary"
    cell_composition_volumes = "cell_composition_volumes"
    single_neuron_synaptome_config = "single_neuron_synaptome_config"
    single_neuron_synaptome_simulation_io_result = "single_neuron_synaptome_simulation_io_result"
    single_cell_simulation_data = "single_cell_simulation_data"
    sonata_circuit = "sonata_circuit"


class AssetStatus(StrEnum):
    created = "created"
    deleted = "deleted"


class BodyUploadEntityAssetEntityRouteEntityIdAssetsPost(BaseModel):
    file: bytes = Field(..., title="File")
    meta: dict[str, Any] | None = Field(None, title="Meta")
    label: AssetLabel | None = None


class BrainRegionRead(BaseModel):
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    id: UUID = Field(..., title="Id")
    annotation_value: int = Field(..., title="Annotation Value")
    name: str = Field(..., title="Name")
    acronym: str = Field(..., title="Acronym")
    color_hex_triplet: str = Field(..., title="Color Hex Triplet")
    parent_structure_id: UUID | None = Field(..., title="Parent Structure Id")
    hierarchy_id: UUID = Field(..., title="Hierarchy Id")


class CircuitBuildCategory(StrEnum):
    computational_model = "computational_model"
    em_reconstruction = "em_reconstruction"


class CircuitScale(StrEnum):
    single = "single"
    pair = "pair"
    small = "small"
    microcircuit = "microcircuit"
    region = "region"
    system = "system"
    whole_brain = "whole_brain"


class ContributionCreate(BaseModel):
    agent_id: UUID = Field(..., title="Agent Id")
    role_id: UUID = Field(..., title="Role Id")
    entity_id: UUID = Field(..., title="Entity Id")


class EModelCreate(BaseModel):
    authorized_public: bool | None = Field(False, title="Authorized Public")
    description: str = Field(..., title="Description")
    name: str = Field(..., title="Name")
    iteration: str = Field(..., title="Iteration")
    score: float = Field(..., title="Score")
    seed: int = Field(..., title="Seed")
    species_id: UUID = Field(..., title="Species Id")
    strain_id: UUID | None = Field(None, title="Strain Id")
    brain_region_id: UUID = Field(..., title="Brain Region Id")
    exemplar_morphology_id: UUID = Field(..., title="Exemplar Morphology Id")


class ETypeClassificationCreate(BaseModel):
    authorized_public: bool | None = Field(False, title="Authorized Public")
    entity_id: UUID = Field(..., title="Entity Id")
    etype_class_id: UUID = Field(..., title="Etype Class Id")


class ElectricalRecordingOrigin(StrEnum):
    in_vivo = "in_vivo"
    in_vitro = "in_vitro"
    in_silico = "in_silico"
    unknown = "unknown"


class ElectricalRecordingStimulusShape(StrEnum):
    cheops = "cheops"
    constant = "constant"
    pulse = "pulse"
    step = "step"
    ramp = "ramp"
    noise = "noise"
    sinusoidal = "sinusoidal"
    other = "other"
    two_steps = "two_steps"
    unknown = "unknown"


class ElectricalRecordingStimulusType(StrEnum):
    voltage_clamp = "voltage_clamp"
    current_clamp = "current_clamp"
    conductance_clamp = "conductance_clamp"
    extracellular = "extracellular"
    other = "other"
    unknown = "unknown"


class ElectricalRecordingType(StrEnum):
    intracellular = "intracellular"
    extracellular = "extracellular"
    both = "both"
    unknown = "unknown"


class EntityRoute(StrEnum):
    analysis_software_source_code = "analysis-software-source-code"
    brain_atlas = "brain-atlas"
    brain_atlas_region = "brain-atlas-region"
    cell_composition = "cell-composition"
    electrical_cell_recording = "electrical-cell-recording"
    electrical_recording_stimulus = "electrical-recording-stimulus"
    emodel = "emodel"
    experimental_bouton_density = "experimental-bouton-density"
    experimental_neuron_density = "experimental-neuron-density"
    experimental_synapses_per_connection = "experimental-synapses-per-connection"
    ion_channel_model = "ion-channel-model"
    memodel = "memodel"
    mesh = "mesh"
    memodel_calibration_result = "memodel-calibration-result"
    me_type_density = "me-type-density"
    publication = "publication"
    reconstruction_morphology = "reconstruction-morphology"
    simulation = "simulation"
    simulation_campaign = "simulation-campaign"
    simulation_campaign_generation = "simulation-campaign-generation"
    simulation_execution = "simulation-execution"
    simulation_result = "simulation-result"
    scientific_artifact = "scientific-artifact"
    single_neuron_simulation = "single-neuron-simulation"
    single_neuron_synaptome = "single-neuron-synaptome"
    single_neuron_synaptome_simulation = "single-neuron-synaptome-simulation"
    subject = "subject"
    validation_result = "validation-result"
    circuit = "circuit"


class EntityType(StrEnum):
    analysis_software_source_code = "analysis_software_source_code"
    brain_atlas = "brain_atlas"
    brain_atlas_region = "brain_atlas_region"
    cell_composition = "cell_composition"
    electrical_cell_recording = "electrical_cell_recording"
    electrical_recording_stimulus = "electrical_recording_stimulus"
    emodel = "emodel"
    experimental_bouton_density = "experimental_bouton_density"
    experimental_neuron_density = "experimental_neuron_density"
    experimental_synapses_per_connection = "experimental_synapses_per_connection"
    ion_channel_model = "ion_channel_model"
    memodel = "memodel"
    mesh = "mesh"
    memodel_calibration_result = "memodel_calibration_result"
    me_type_density = "me_type_density"
    publication = "publication"
    reconstruction_morphology = "reconstruction_morphology"
    simulation = "simulation"
    simulation_campaign = "simulation_campaign"
    simulation_campaign_generation = "simulation_campaign_generation"
    simulation_execution = "simulation_execution"
    simulation_result = "simulation_result"
    scientific_artifact = "scientific_artifact"
    single_neuron_simulation = "single_neuron_simulation"
    single_neuron_synaptome = "single_neuron_synaptome"
    single_neuron_synaptome_simulation = "single_neuron_synaptome_simulation"
    subject = "subject"
    validation_result = "validation_result"
    circuit = "circuit"


class ErrorResponse(BaseModel):
    error_code: ApiErrorCode
    message: str = Field(..., title="Message")
    details: Any | None = Field(None, title="Details")


class ExperimentalBoutonDensityCreate(BaseModel):
    authorized_public: bool | None = Field(False, title="Authorized Public")
    license_id: UUID | None = Field(None, title="License Id")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    subject_id: UUID = Field(..., title="Subject Id")
    brain_region_id: UUID = Field(..., title="Brain Region Id")
    legacy_id: str | None = Field(..., title="Legacy Id")


class ExperimentalNeuronDensityCreate(BaseModel):
    authorized_public: bool | None = Field(False, title="Authorized Public")
    license_id: UUID | None = Field(None, title="License Id")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    subject_id: UUID = Field(..., title="Subject Id")
    brain_region_id: UUID = Field(..., title="Brain Region Id")
    legacy_id: str | None = Field(..., title="Legacy Id")


class ExperimentalSynapsesPerConnectionCreate(BaseModel):
    authorized_public: bool | None = Field(False, title="Authorized Public")
    license_id: UUID | None = Field(None, title="License Id")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    subject_id: UUID = Field(..., title="Subject Id")
    brain_region_id: UUID = Field(..., title="Brain Region Id")
    legacy_id: str | None = Field(..., title="Legacy Id")
    pre_mtype_id: UUID = Field(..., title="Pre Mtype Id")
    post_mtype_id: UUID = Field(..., title="Post Mtype Id")
    pre_region_id: UUID = Field(..., title="Pre Region Id")
    post_region_id: UUID = Field(..., title="Post Region Id")


class Facet(BaseModel):
    id: UUID | int = Field(..., title="Id")
    label: str = Field(..., title="Label")
    count: int = Field(..., title="Count")
    type: str | None = Field(..., title="Type")


class Facets(RootModel[dict[str, list[Facet]] | None]):
    root: dict[str, list[Facet]] | None = None


class LicenseCreate(BaseModel):
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    label: str = Field(..., title="Label")


class LicenseRead(BaseModel):
    id: UUID = Field(..., title="Id")
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    label: str = Field(..., title="Label")


class MEModelCalibrationResultCreate(BaseModel):
    holding_current: float = Field(..., title="Holding Current")
    threshold_current: float = Field(..., title="Threshold Current")
    rin: float | None = Field(None, title="Rin")
    calibrated_entity_id: UUID = Field(..., title="Calibrated Entity Id")


class MTypeClassificationCreate(BaseModel):
    authorized_public: bool | None = Field(False, title="Authorized Public")
    entity_id: UUID = Field(..., title="Entity Id")
    mtype_class_id: UUID = Field(..., title="Mtype Class Id")


class MeasurableEntity(StrEnum):
    reconstruction_morphology = "reconstruction_morphology"


class MeasurementStatistic(StrEnum):
    mean = "mean"
    median = "median"
    mode = "mode"
    variance = "variance"
    data_point = "data_point"
    sample_size = "sample_size"
    standard_error = "standard_error"
    standard_deviation = "standard_deviation"
    raw = "raw"
    minimum = "minimum"
    maximum = "maximum"
    sum = "sum"


class MeasurementUnit(StrEnum):
    dimensionless = "dimensionless"
    field_1_μm = "1/μm"
    field_1_mm_ = "1/mm³"
    μm = "μm"
    μm_ = "μm²"
    μm__1 = "μm³"
    radian = "radian"


class NestedEntityRead(BaseModel):
    id: UUID = Field(..., title="Id")
    type: str = Field(..., title="Type")
    authorized_project_id: UUID4 = Field(..., title="Authorized Project Id")
    authorized_public: bool = Field(..., title="Authorized Public")


class NestedOrganizationRead(BaseModel):
    id: UUID = Field(..., title="Id")
    pref_label: str = Field(..., title="Pref Label")
    alternative_name: str | None = Field(None, title="Alternative Name")
    type: str = Field(..., title="Type")


class NestedPersonRead(BaseModel):
    id: UUID = Field(..., title="Id")
    given_name: str | None = Field(None, title="Given Name")
    family_name: str | None = Field(None, title="Family Name")
    pref_label: str = Field(..., title="Pref Label")
    type: str = Field(..., title="Type")
    sub_id: UUID | None = Field(..., title="Sub Id")


class NestedSimulationRead(BaseModel):
    id: UUID = Field(..., title="Id")
    type: EntityType | None = None
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    simulation_campaign_id: UUID = Field(..., title="Simulation Campaign Id")
    entity_id: UUID = Field(..., title="Entity Id")
    scan_parameters: dict[str, Any] = Field(..., title="Scan Parameters")


class NestedSpeciesRead(BaseModel):
    id: UUID = Field(..., title="Id")
    name: str = Field(..., title="Name")
    taxonomy_id: str = Field(..., title="Taxonomy Id")


class NestedStrainRead(BaseModel):
    id: UUID = Field(..., title="Id")
    name: str = Field(..., title="Name")
    taxonomy_id: str = Field(..., title="Taxonomy Id")
    species_id: UUID = Field(..., title="Species Id")


class NestedSynaptome(BaseModel):
    id: UUID = Field(..., title="Id")
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    seed: int = Field(..., title="Seed")


class OrganizationCreate(BaseModel):
    pref_label: str = Field(..., title="Pref Label")
    alternative_name: str | None = Field(None, title="Alternative Name")
    legacy_id: str | None = Field(None, title="Legacy Id")


class OrganizationRead(BaseModel):
    id: UUID = Field(..., title="Id")
    created_by: NestedPersonRead
    updated_by: NestedPersonRead
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    pref_label: str = Field(..., title="Pref Label")
    alternative_name: str | None = Field(None, title="Alternative Name")
    type: str = Field(..., title="Type")


class PaginationResponse(BaseModel):
    page: int = Field(..., title="Page")
    page_size: int = Field(..., title="Page Size")
    total_items: int = Field(..., title="Total Items")


class PersonCreate(BaseModel):
    given_name: str | None = Field(None, title="Given Name")
    family_name: str | None = Field(None, title="Family Name")
    pref_label: str = Field(..., title="Pref Label")
    legacy_id: str | None = Field(None, title="Legacy Id")


class PersonRead(BaseModel):
    created_by: NestedPersonRead
    updated_by: NestedPersonRead
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    id: UUID = Field(..., title="Id")
    given_name: str | None = Field(None, title="Given Name")
    family_name: str | None = Field(None, title="Family Name")
    pref_label: str = Field(..., title="Pref Label")
    type: str = Field(..., title="Type")
    sub_id: UUID | None = Field(..., title="Sub Id")


class PointLocationBase(BaseModel):
    x: float = Field(..., title="X")
    y: float = Field(..., title="Y")
    z: float = Field(..., title="Z")


class ReconstructionMorphologyCreate(BaseModel):
    authorized_public: bool | None = Field(False, title="Authorized Public")
    license_id: UUID | None = Field(None, title="License Id")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    location: PointLocationBase | None = None
    legacy_id: list[str] | None = Field(None, title="Legacy Id")
    species_id: UUID = Field(..., title="Species Id")
    strain_id: UUID | None = Field(None, title="Strain Id")
    brain_region_id: UUID = Field(..., title="Brain Region Id")


class RoleCreate(BaseModel):
    name: str = Field(..., title="Name")
    role_id: str = Field(..., title="Role Id")


class RoleRead(BaseModel):
    id: UUID = Field(..., title="Id")
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    name: str = Field(..., title="Name")
    role_id: str = Field(..., title="Role Id")


class Sex(StrEnum):
    male = "male"
    female = "female"
    unknown = "unknown"


class SimulationCampaignCreate(BaseModel):
    authorized_public: bool | None = Field(False, title="Authorized Public")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    scan_parameters: dict[str, Any] = Field(..., title="Scan Parameters")
    entity_id: UUID = Field(..., title="Entity Id")


class SimulationCreate(BaseModel):
    authorized_public: bool | None = Field(False, title="Authorized Public")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    simulation_campaign_id: UUID = Field(..., title="Simulation Campaign Id")
    entity_id: UUID = Field(..., title="Entity Id")
    scan_parameters: dict[str, Any] = Field(..., title="Scan Parameters")


class SimulationExecutionStatus(StrEnum):
    created = "created"
    pending = "pending"
    running = "running"
    done = "done"
    error = "error"


class SimulationExecutionUpdate(BaseModel):
    authorized_public: bool | None = Field(False, title="Authorized Public")
    start_time: datetime | None = Field(None, title="Start Time")
    end_time: datetime | None = Field(None, title="End Time")
    generated_ids: list[UUID] | None = Field(None, title="Generated Ids")
    status: SimulationExecutionStatus | None = None


class SimulationGenerationCreate(BaseModel):
    authorized_public: bool | None = Field(False, title="Authorized Public")
    start_time: datetime | None = Field(None, title="Start Time")
    end_time: datetime | None = Field(None, title="End Time")
    used_ids: list[UUID] | None = Field([], title="Used Ids")
    generated_ids: list[UUID] | None = Field([], title="Generated Ids")


class SimulationGenerationRead(BaseModel):
    authorized_project_id: UUID4 = Field(..., title="Authorized Project Id")
    authorized_public: bool | None = Field(False, title="Authorized Public")
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    created_by: NestedPersonRead
    updated_by: NestedPersonRead
    id: UUID = Field(..., title="Id")
    type: ActivityType | None = None
    start_time: datetime | None = Field(None, title="Start Time")
    end_time: datetime | None = Field(None, title="End Time")
    used: list[NestedEntityRead] = Field(..., title="Used")
    generated: list[NestedEntityRead] = Field(..., title="Generated")


class SimulationGenerationUpdate(BaseModel):
    authorized_public: bool | None = Field(False, title="Authorized Public")
    start_time: datetime | None = Field(None, title="Start Time")
    end_time: datetime | None = Field(None, title="End Time")
    generated_ids: list[UUID] | None = Field(None, title="Generated Ids")


class SimulationResultCreate(BaseModel):
    authorized_public: bool | None = Field(False, title="Authorized Public")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")


class SingleNeuronSimulationStatus(StrEnum):
    started = "started"
    failure = "failure"
    success = "success"


class SingleNeuronSynaptomeCreate(BaseModel):
    authorized_public: bool | None = Field(False, title="Authorized Public")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    seed: int = Field(..., title="Seed")
    me_model_id: UUID = Field(..., title="Me Model Id")
    brain_region_id: UUID = Field(..., title="Brain Region Id")


class SingleNeuronSynaptomeSimulationCreate(BaseModel):
    brain_region_id: UUID = Field(..., title="Brain Region Id")
    authorized_public: bool | None = Field(False, title="Authorized Public")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    seed: int = Field(..., title="Seed")
    status: SingleNeuronSimulationStatus
    injection_location: list[str] = Field(..., title="Injection Location")
    recording_location: list[str] = Field(..., title="Recording Location")
    synaptome_id: UUID = Field(..., title="Synaptome Id")


class SpeciesCreate(BaseModel):
    name: str = Field(..., title="Name")
    taxonomy_id: str = Field(..., title="Taxonomy Id")


class SpeciesRead(BaseModel):
    id: UUID = Field(..., title="Id")
    created_by: NestedPersonRead
    updated_by: NestedPersonRead
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    name: str = Field(..., title="Name")
    taxonomy_id: str = Field(..., title="Taxonomy Id")


class StrainCreate(BaseModel):
    name: str = Field(..., title="Name")
    taxonomy_id: str = Field(..., title="Taxonomy Id")
    species_id: UUID = Field(..., title="Species Id")


class StrainRead(BaseModel):
    id: UUID = Field(..., title="Id")
    created_by: NestedPersonRead
    updated_by: NestedPersonRead
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    name: str = Field(..., title="Name")
    taxonomy_id: str = Field(..., title="Taxonomy Id")
    species_id: UUID = Field(..., title="Species Id")


class StructuralDomain(StrEnum):
    apical_dendrite = "apical_dendrite"
    basal_dendrite = "basal_dendrite"
    axon = "axon"
    soma = "soma"
    neuron_morphology = "neuron_morphology"


class SubjectCreate(BaseModel):
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    sex: Sex = Field(..., description="Sex of the subject", title="Sex")
    weight: PositiveFloat | None = Field(None, description="Weight in grams", title="Weight")
    age_value: float | None = Field(None, description="Age value interval.", title="Age value")
    age_min: float | None = Field(None, description="Minimum age range", title="Minimum age range")
    age_max: float | None = Field(None, description="Maximum age range", title="Maximum age range")
    age_period: AgePeriod | None = None
    authorized_public: bool | None = Field(False, title="Authorized Public")
    species_id: UUID = Field(..., title="Species Id")


class SubjectRead(BaseModel):
    id: UUID = Field(..., title="Id")
    authorized_project_id: UUID4 = Field(..., title="Authorized Project Id")
    authorized_public: bool | None = Field(False, title="Authorized Public")
    created_by: NestedPersonRead
    updated_by: NestedPersonRead
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    sex: Sex = Field(..., description="Sex of the subject")
    weight: PositiveFloat | None = Field(None, description="Weight in grams", title="Weight")
    age_value: float | None = Field(None, description="Age value interval.", title="Age value")
    age_min: float | None = Field(None, description="Minimum age range", title="Minimum age range")
    age_max: float | None = Field(None, description="Maximum age range", title="Maximum age range")
    age_period: AgePeriod | None = None
    species: NestedSpeciesRead


class UseIon(BaseModel):
    ion_name: str = Field(..., title="Ion Name")
    read: list[str] | None = Field([], title="Read")
    write: list[str] | None = Field([], title="Write")
    valence: int | None = Field(None, title="Valence")
    main_ion: bool | None = Field(None, title="Main Ion")


class ValidationResultCreate(BaseModel):
    name: str = Field(..., title="Name")
    passed: bool = Field(..., title="Passed")
    validated_entity_id: UUID = Field(..., title="Validated Entity Id")


class ValidationResultRead(BaseModel):
    created_by: NestedPersonRead
    updated_by: NestedPersonRead
    id: UUID = Field(..., title="Id")
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    name: str = Field(..., title="Name")
    passed: bool = Field(..., title="Passed")
    validated_entity_id: UUID = Field(..., title="Validated Entity Id")


class ValidationStatus(StrEnum):
    created = "created"
    initialized = "initialized"
    running = "running"
    done = "done"
    error = "error"


class AgentRead(RootModel[NestedPersonRead | NestedOrganizationRead]):
    root: NestedPersonRead | NestedOrganizationRead


class AssetRead(BaseModel):
    path: str = Field(..., title="Path")
    full_path: str = Field(..., title="Full Path")
    is_directory: bool = Field(..., title="Is Directory")
    content_type: str = Field(..., title="Content Type")
    size: int = Field(..., title="Size")
    sha256_digest: str | None = Field(..., title="Sha256 Digest")
    meta: dict[str, Any] = Field(..., title="Meta")
    label: AssetLabel | None = None
    id: UUID = Field(..., title="Id")
    status: AssetStatus


class BasicEntityRead(BaseModel):
    type: EntityType | None = None
    id: UUID = Field(..., title="Id")


class BrainAtlasRead(BaseModel):
    assets: list[AssetRead] = Field(..., title="Assets")
    id: UUID = Field(..., title="Id")
    created_by: NestedPersonRead
    updated_by: NestedPersonRead
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    name: str = Field(..., title="Name")
    hierarchy_id: UUID = Field(..., title="Hierarchy Id")
    species: NestedSpeciesRead


class BrainAtlasRegionRead(BaseModel):
    assets: list[AssetRead] = Field(..., title="Assets")
    id: UUID = Field(..., title="Id")
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    volume: float | None = Field(..., title="Volume")
    is_leaf_region: bool = Field(..., title="Is Leaf Region")
    brain_atlas_id: UUID = Field(..., title="Brain Atlas Id")
    brain_region_id: UUID = Field(..., title="Brain Region Id")


class BrainRegionHierarchyRead(BaseModel):
    id: UUID = Field(..., title="Id")
    created_by: NestedPersonRead
    updated_by: NestedPersonRead
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    name: str = Field(..., title="Name")


class CircuitCreate(BaseModel):
    authorized_public: bool | None = Field(False, title="Authorized Public")
    license_id: UUID | None = Field(None, title="License Id")
    brain_region_id: UUID = Field(..., title="Brain Region Id")
    subject_id: UUID = Field(..., title="Subject Id")
    experiment_date: datetime | None = Field(None, title="Experiment Date")
    contact_id: UUID | None = Field(None, title="Contact Id")
    atlas_id: UUID | None = Field(None, title="Atlas Id")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    has_morphologies: bool | None = Field(False, title="Has Morphologies")
    has_point_neurons: bool | None = Field(False, title="Has Point Neurons")
    has_electrical_cell_models: bool | None = Field(False, title="Has Electrical Cell Models")
    has_spines: bool | None = Field(False, title="Has Spines")
    number_neurons: int = Field(..., title="Number Neurons")
    number_synapses: int = Field(..., title="Number Synapses")
    number_connections: int | None = Field(..., title="Number Connections")
    scale: CircuitScale
    build_category: CircuitBuildCategory
    root_circuit_id: UUID | None = Field(None, title="Root Circuit Id")


class ContributionRead(BaseModel):
    id: UUID = Field(..., title="Id")
    created_by: NestedPersonRead
    updated_by: NestedPersonRead
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    agent: AgentRead
    role: RoleRead
    entity: NestedEntityRead


class ETypeClassificationRead(BaseModel):
    authorized_project_id: UUID4 = Field(..., title="Authorized Project Id")
    authorized_public: bool | None = Field(False, title="Authorized Public")
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    created_by: NestedPersonRead
    updated_by: NestedPersonRead
    entity_id: UUID = Field(..., title="Entity Id")
    etype_class_id: UUID = Field(..., title="Etype Class Id")


class ElectricalCellRecordingCreate(BaseModel):
    authorized_public: bool | None = Field(False, title="Authorized Public")
    license_id: UUID | None = Field(None, title="License Id")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    ljp: float | None = Field(
        0.0,
        description="Correction applied to the voltage trace, in mV",
        title="Liquid Junction Potential",
    )
    recording_location: list[str] = Field(
        ...,
        description="Location on the cell where recording was performed, in hoc-compatible format.",
        title="Recording Location",
    )
    recording_type: ElectricalRecordingType = Field(
        ...,
        description="Recording type. One of: [<ElectricalRecordingStimulusType.conductance_clamp: 'conductance_clamp'>, <ElectricalRecordingStimulusType.current_clamp: 'current_clamp'>, <ElectricalRecordingStimulusType.extracellular: 'extracellular'>, <ElectricalRecordingStimulusType.other: 'other'>, <ElectricalRecordingStimulusType.unknown: 'unknown'>, <ElectricalRecordingStimulusType.voltage_clamp: 'voltage_clamp'>]",
        title="Recording Type",
    )
    recording_origin: ElectricalRecordingOrigin = Field(
        ...,
        description="Recording origin. One of: [<ElectricalRecordingOrigin.in_silico: 'in_silico'>, <ElectricalRecordingOrigin.in_vitro: 'in_vitro'>, <ElectricalRecordingOrigin.in_vivo: 'in_vivo'>, <ElectricalRecordingOrigin.unknown: 'unknown'>]",
        title="Recording Origin",
    )
    comment: str | None = Field(None, description="Comment with further details.", title="Comment")
    legacy_id: list[str] | None = Field(None, title="Legacy Id")
    subject_id: UUID = Field(..., title="Subject Id")
    brain_region_id: UUID | None = Field(None, title="Brain Region Id")


class ElectricalRecordingStimulusRead(BaseModel):
    type: EntityType | None = None
    id: UUID = Field(..., title="Id")
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    dt: float | None = Field(None, title="Dt")
    injection_type: ElectricalRecordingStimulusType
    shape: ElectricalRecordingStimulusShape
    start_time: float | None = Field(None, title="Start Time")
    end_time: float | None = Field(None, title="End Time")


class ExemplarMorphology(BaseModel):
    id: UUID = Field(..., title="Id")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    location: PointLocationBase | None = None
    legacy_id: list[str] | None = Field(..., title="Legacy Id")
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")


class ListResponseAnnotation(BaseModel):
    data: list[Annotation] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class ListResponseAssetRead(BaseModel):
    data: list[AssetRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class ListResponseBasicEntityRead(BaseModel):
    data: list[BasicEntityRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class ListResponseBrainAtlasRead(BaseModel):
    data: list[BrainAtlasRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class ListResponseBrainAtlasRegionRead(BaseModel):
    data: list[BrainAtlasRegionRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class ListResponseBrainRegionHierarchyRead(BaseModel):
    data: list[BrainRegionHierarchyRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class ListResponseBrainRegionRead(BaseModel):
    data: list[BrainRegionRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class ListResponseContributionRead(BaseModel):
    data: list[ContributionRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class ListResponseLicenseRead(BaseModel):
    data: list[LicenseRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class ListResponseOrganizationRead(BaseModel):
    data: list[OrganizationRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class ListResponsePersonRead(BaseModel):
    data: list[PersonRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class ListResponseRoleRead(BaseModel):
    data: list[RoleRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class ListResponseSimulationGenerationRead(BaseModel):
    data: list[SimulationGenerationRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class ListResponseSpeciesRead(BaseModel):
    data: list[SpeciesRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class ListResponseStrainRead(BaseModel):
    data: list[StrainRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class ListResponseSubjectRead(BaseModel):
    data: list[SubjectRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class ListResponseValidationResultRead(BaseModel):
    data: list[ValidationResultRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class MEModelCalibrationResultRead(BaseModel):
    created_by: NestedPersonRead
    updated_by: NestedPersonRead
    id: UUID = Field(..., title="Id")
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    holding_current: float = Field(..., title="Holding Current")
    threshold_current: float = Field(..., title="Threshold Current")
    rin: float | None = Field(None, title="Rin")
    calibrated_entity_id: UUID = Field(..., title="Calibrated Entity Id")


class MEModelCreate(BaseModel):
    authorized_public: bool | None = Field(False, title="Authorized Public")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    validation_status: ValidationStatus | None = "created"
    brain_region_id: UUID = Field(..., title="Brain Region Id")
    morphology_id: UUID = Field(..., title="Morphology Id")
    emodel_id: UUID = Field(..., title="Emodel Id")
    species_id: UUID = Field(..., title="Species Id")
    strain_id: UUID | None = Field(None, title="Strain Id")


class MTypeClassificationRead(BaseModel):
    authorized_project_id: UUID4 = Field(..., title="Authorized Project Id")
    authorized_public: bool | None = Field(False, title="Authorized Public")
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    created_by: NestedPersonRead
    updated_by: NestedPersonRead
    entity_id: UUID = Field(..., title="Entity Id")
    mtype_class_id: UUID = Field(..., title="Mtype Class Id")


class MeasurementItem(BaseModel):
    name: MeasurementStatistic | None = None
    unit: MeasurementUnit | None = None
    value: float | None = Field(..., title="Value")


class MeasurementKindCreate(BaseModel):
    structural_domain: StructuralDomain
    measurement_items: list[MeasurementItem] = Field(..., title="Measurement Items")
    pref_label: str = Field(..., title="Pref Label")


class MeasurementKindRead(BaseModel):
    structural_domain: StructuralDomain
    measurement_items: list[MeasurementItem] = Field(..., title="Measurement Items")
    pref_label: str = Field(..., title="Pref Label")


class MeasurementRead(BaseModel):
    id: int = Field(..., title="Id")
    name: str = Field(..., title="Name")
    unit: MeasurementUnit
    value: float = Field(..., title="Value")


class NestedContributionRead(BaseModel):
    id: UUID = Field(..., title="Id")
    agent: AgentRead
    role: RoleRead


class NestedMEModel(BaseModel):
    id: UUID = Field(..., title="Id")
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    validation_status: ValidationStatus | None = "created"
    mtypes: list[Annotation] | None = Field(..., title="Mtypes")
    etypes: list[Annotation] | None = Field(..., title="Etypes")


class NestedSubjectRead(BaseModel):
    id: UUID = Field(..., title="Id")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    sex: Sex = Field(..., description="Sex of the subject")
    weight: PositiveFloat | None = Field(None, description="Weight in grams", title="Weight")
    age_value: float | None = Field(None, description="Age value interval.", title="Age value")
    age_min: float | None = Field(None, description="Minimum age range", title="Minimum age range")
    age_max: float | None = Field(None, description="Maximum age range", title="Maximum age range")
    age_period: AgePeriod | None = None
    species: NestedSpeciesRead


class NeuronBlock(BaseModel):
    global_: list[dict[str, str | None]] | None = Field([], alias="global", title="Global")
    range: list[dict[str, str | None]] | None = Field([], title="Range")
    useion: list[UseIon] | None = Field([], title="Useion")
    nonspecific: list[dict[str, str | None]] | None = Field([], title="Nonspecific")


class ReconstructionMorphologyRead(BaseModel):
    contributions: list[NestedContributionRead] | None = Field(..., title="Contributions")
    created_by: NestedPersonRead
    updated_by: NestedPersonRead
    type: EntityType | None = None
    assets: list[AssetRead] = Field(..., title="Assets")
    authorized_project_id: UUID4 = Field(..., title="Authorized Project Id")
    authorized_public: bool | None = Field(False, title="Authorized Public")
    license: LicenseRead | None = None
    id: UUID = Field(..., title="Id")
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    location: PointLocationBase | None = None
    legacy_id: list[str] | None = Field(..., title="Legacy Id")
    species: NestedSpeciesRead
    strain: NestedStrainRead | None = None
    brain_region: BrainRegionRead
    mtypes: list[Annotation] | None = Field(..., title="Mtypes")


class SimulationCampaignRead(BaseModel):
    authorized_project_id: UUID4 = Field(..., title="Authorized Project Id")
    authorized_public: bool | None = Field(False, title="Authorized Public")
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    created_by: NestedPersonRead
    updated_by: NestedPersonRead
    assets: list[AssetRead] = Field(..., title="Assets")
    id: UUID = Field(..., title="Id")
    type: EntityType | None = None
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    scan_parameters: dict[str, Any] = Field(..., title="Scan Parameters")
    entity_id: UUID = Field(..., title="Entity Id")
    simulations: list[NestedSimulationRead] = Field(..., title="Simulations")


class SimulationExecutionCreate(BaseModel):
    authorized_public: bool | None = Field(False, title="Authorized Public")
    start_time: datetime | None = Field(None, title="Start Time")
    end_time: datetime | None = Field(None, title="End Time")
    used_ids: list[UUID] | None = Field([], title="Used Ids")
    generated_ids: list[UUID] | None = Field([], title="Generated Ids")
    status: SimulationExecutionStatus


class SimulationExecutionRead(BaseModel):
    authorized_project_id: UUID4 = Field(..., title="Authorized Project Id")
    authorized_public: bool | None = Field(False, title="Authorized Public")
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    created_by: NestedPersonRead
    updated_by: NestedPersonRead
    id: UUID = Field(..., title="Id")
    type: ActivityType | None = None
    start_time: datetime | None = Field(None, title="Start Time")
    end_time: datetime | None = Field(None, title="End Time")
    used: list[NestedEntityRead] = Field(..., title="Used")
    generated: list[NestedEntityRead] = Field(..., title="Generated")
    status: SimulationExecutionStatus


class SimulationRead(BaseModel):
    authorized_project_id: UUID4 = Field(..., title="Authorized Project Id")
    authorized_public: bool | None = Field(False, title="Authorized Public")
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    created_by: NestedPersonRead
    updated_by: NestedPersonRead
    assets: list[AssetRead] = Field(..., title="Assets")
    id: UUID = Field(..., title="Id")
    type: EntityType | None = None
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    simulation_campaign_id: UUID = Field(..., title="Simulation Campaign Id")
    entity_id: UUID = Field(..., title="Entity Id")
    scan_parameters: dict[str, Any] = Field(..., title="Scan Parameters")


class SimulationResultRead(BaseModel):
    authorized_project_id: UUID4 = Field(..., title="Authorized Project Id")
    authorized_public: bool | None = Field(False, title="Authorized Public")
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    created_by: NestedPersonRead
    updated_by: NestedPersonRead
    assets: list[AssetRead] = Field(..., title="Assets")
    id: UUID = Field(..., title="Id")
    type: EntityType | None = None
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")


class SingleNeuronSimulationCreate(BaseModel):
    brain_region_id: UUID = Field(..., title="Brain Region Id")
    authorized_public: bool | None = Field(False, title="Authorized Public")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    seed: int = Field(..., title="Seed")
    status: SingleNeuronSimulationStatus
    injection_location: list[str] = Field(..., title="Injection Location")
    recording_location: list[str] = Field(..., title="Recording Location")
    me_model_id: UUID = Field(..., title="Me Model Id")


class SingleNeuronSimulationRead(BaseModel):
    created_by: NestedPersonRead
    updated_by: NestedPersonRead
    assets: list[AssetRead] = Field(..., title="Assets")
    type: EntityType | None = None
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    id: UUID = Field(..., title="Id")
    authorized_project_id: UUID4 = Field(..., title="Authorized Project Id")
    authorized_public: bool | None = Field(False, title="Authorized Public")
    brain_region: BrainRegionRead
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    seed: int = Field(..., title="Seed")
    status: SingleNeuronSimulationStatus
    injection_location: list[str] = Field(..., title="Injection Location")
    recording_location: list[str] = Field(..., title="Recording Location")
    me_model: NestedMEModel


class SingleNeuronSynaptomeRead(BaseModel):
    created_by: NestedPersonRead
    updated_by: NestedPersonRead
    assets: list[AssetRead] = Field(..., title="Assets")
    type: EntityType | None = None
    contributions: list[NestedContributionRead] | None = Field(..., title="Contributions")
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    id: UUID = Field(..., title="Id")
    authorized_project_id: UUID4 = Field(..., title="Authorized Project Id")
    authorized_public: bool | None = Field(False, title="Authorized Public")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    seed: int = Field(..., title="Seed")
    me_model: NestedMEModel
    brain_region: BrainRegionRead


class SingleNeuronSynaptomeSimulationRead(BaseModel):
    created_by: NestedPersonRead
    updated_by: NestedPersonRead
    assets: list[AssetRead] = Field(..., title="Assets")
    type: EntityType | None = None
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    id: UUID = Field(..., title="Id")
    authorized_project_id: UUID4 = Field(..., title="Authorized Project Id")
    authorized_public: bool | None = Field(False, title="Authorized Public")
    brain_region: BrainRegionRead
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    seed: int = Field(..., title="Seed")
    status: SingleNeuronSimulationStatus
    injection_location: list[str] = Field(..., title="Injection Location")
    recording_location: list[str] = Field(..., title="Recording Location")
    synaptome: NestedSynaptome


class CircuitRead(BaseModel):
    assets: list[AssetRead] = Field(..., title="Assets")
    authorized_project_id: UUID4 = Field(..., title="Authorized Project Id")
    authorized_public: bool | None = Field(False, title="Authorized Public")
    id: UUID = Field(..., title="Id")
    type: EntityType | None = None
    license: LicenseRead | None = None
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    created_by: NestedPersonRead
    updated_by: NestedPersonRead
    brain_region: BrainRegionRead
    subject: NestedSubjectRead
    experiment_date: datetime | None = Field(None, title="Experiment Date")
    contact_id: UUID | None = Field(None, title="Contact Id")
    atlas_id: UUID | None = Field(None, title="Atlas Id")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    has_morphologies: bool | None = Field(False, title="Has Morphologies")
    has_point_neurons: bool | None = Field(False, title="Has Point Neurons")
    has_electrical_cell_models: bool | None = Field(False, title="Has Electrical Cell Models")
    has_spines: bool | None = Field(False, title="Has Spines")
    number_neurons: int = Field(..., title="Number Neurons")
    number_synapses: int = Field(..., title="Number Synapses")
    number_connections: int | None = Field(..., title="Number Connections")
    scale: CircuitScale
    build_category: CircuitBuildCategory
    root_circuit_id: UUID | None = Field(None, title="Root Circuit Id")


class EModelRead(BaseModel):
    contributions: list[NestedContributionRead] | None = Field(..., title="Contributions")
    created_by: NestedPersonRead
    updated_by: NestedPersonRead
    assets: list[AssetRead] = Field(..., title="Assets")
    type: EntityType | None = None
    authorized_project_id: UUID4 = Field(..., title="Authorized Project Id")
    authorized_public: bool | None = Field(False, title="Authorized Public")
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    description: str = Field(..., title="Description")
    name: str = Field(..., title="Name")
    iteration: str = Field(..., title="Iteration")
    score: float = Field(..., title="Score")
    seed: int = Field(..., title="Seed")
    id: UUID = Field(..., title="Id")
    species: NestedSpeciesRead
    strain: NestedStrainRead | None = None
    brain_region: BrainRegionRead
    mtypes: list[Annotation] | None = Field(..., title="Mtypes")
    etypes: list[Annotation] | None = Field(..., title="Etypes")
    exemplar_morphology: ExemplarMorphology


class ElectricalCellRecordingRead(BaseModel):
    subject: NestedSubjectRead
    created_by: NestedPersonRead
    updated_by: NestedPersonRead
    type: EntityType | None = None
    id: UUID = Field(..., title="Id")
    authorized_project_id: UUID4 = Field(..., title="Authorized Project Id")
    authorized_public: bool | None = Field(False, title="Authorized Public")
    license: LicenseRead | None = None
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    ljp: float | None = Field(
        0.0,
        description="Correction applied to the voltage trace, in mV",
        title="Liquid Junction Potential",
    )
    recording_location: list[str] = Field(
        ...,
        description="Location on the cell where recording was performed, in hoc-compatible format.",
        title="Recording Location",
    )
    recording_type: ElectricalRecordingType = Field(
        ...,
        description="Recording type. One of: [<ElectricalRecordingStimulusType.conductance_clamp: 'conductance_clamp'>, <ElectricalRecordingStimulusType.current_clamp: 'current_clamp'>, <ElectricalRecordingStimulusType.extracellular: 'extracellular'>, <ElectricalRecordingStimulusType.other: 'other'>, <ElectricalRecordingStimulusType.unknown: 'unknown'>, <ElectricalRecordingStimulusType.voltage_clamp: 'voltage_clamp'>]",
        title="Recording Type",
    )
    recording_origin: ElectricalRecordingOrigin = Field(
        ...,
        description="Recording origin. One of: [<ElectricalRecordingOrigin.in_silico: 'in_silico'>, <ElectricalRecordingOrigin.in_vitro: 'in_vitro'>, <ElectricalRecordingOrigin.in_vivo: 'in_vivo'>, <ElectricalRecordingOrigin.unknown: 'unknown'>]",
        title="Recording Origin",
    )
    comment: str | None = Field(None, description="Comment with further details.", title="Comment")
    legacy_id: list[str] | None = Field(None, title="Legacy Id")
    brain_region: BrainRegionRead
    assets: list[AssetRead] | None = Field(..., title="Assets")
    stimuli: list[ElectricalRecordingStimulusRead] | None = Field(
        None,
        description="List of stimuli applied to the cell with their respective time steps",
        title="Electrical Recording Stimuli",
    )


class ExperimentalBoutonDensityRead(BaseModel):
    subject: NestedSubjectRead
    contributions: list[NestedContributionRead] | None = Field(..., title="Contributions")
    created_by: NestedPersonRead
    updated_by: NestedPersonRead
    type: EntityType | None = None
    authorized_project_id: UUID4 = Field(..., title="Authorized Project Id")
    authorized_public: bool | None = Field(False, title="Authorized Public")
    license: LicenseRead | None = None
    id: UUID = Field(..., title="Id")
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    measurements: list[MeasurementRead] | None = Field(..., title="Measurements")
    assets: list[AssetRead] | None = Field(..., title="Assets")
    brain_region: BrainRegionRead
    mtypes: list[Annotation] | None = Field(..., title="Mtypes")


class ExperimentalNeuronDensityRead(BaseModel):
    subject: NestedSubjectRead
    contributions: list[NestedContributionRead] | None = Field(..., title="Contributions")
    created_by: NestedPersonRead
    updated_by: NestedPersonRead
    type: EntityType | None = None
    authorized_project_id: UUID4 = Field(..., title="Authorized Project Id")
    authorized_public: bool | None = Field(False, title="Authorized Public")
    license: LicenseRead | None = None
    id: UUID = Field(..., title="Id")
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    measurements: list[MeasurementRead] | None = Field(..., title="Measurements")
    assets: list[AssetRead] | None = Field(..., title="Assets")
    brain_region: BrainRegionRead
    mtypes: list[Annotation] | None = Field(..., title="Mtypes")
    etypes: list[Annotation] | None = Field(..., title="Etypes")


class ExperimentalSynapsesPerConnectionRead(BaseModel):
    subject: NestedSubjectRead
    contributions: list[NestedContributionRead] | None = Field(..., title="Contributions")
    created_by: NestedPersonRead
    updated_by: NestedPersonRead
    type: EntityType | None = None
    authorized_project_id: UUID4 = Field(..., title="Authorized Project Id")
    authorized_public: bool | None = Field(False, title="Authorized Public")
    license: LicenseRead | None = None
    id: UUID = Field(..., title="Id")
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    measurements: list[MeasurementRead] | None = Field(..., title="Measurements")
    assets: list[AssetRead] | None = Field(..., title="Assets")
    brain_region: BrainRegionRead
    pre_mtype: Annotation
    post_mtype: Annotation
    pre_region: BrainRegionRead
    post_region: BrainRegionRead


class IonChannelModelCreate(BaseModel):
    authorized_public: bool | None = Field(False, title="Authorized Public")
    description: str = Field(..., title="Description")
    name: str = Field(..., title="Name")
    nmodl_suffix: str = Field(..., title="Nmodl Suffix")
    is_ljp_corrected: bool | None = Field(False, title="Is Ljp Corrected")
    is_temperature_dependent: bool | None = Field(False, title="Is Temperature Dependent")
    temperature_celsius: int = Field(..., title="Temperature Celsius")
    is_stochastic: bool | None = Field(False, title="Is Stochastic")
    neuron_block: NeuronBlock
    species_id: UUID = Field(..., title="Species Id")
    strain_id: UUID | None = Field(None, title="Strain Id")
    brain_region_id: UUID = Field(..., title="Brain Region Id")


class IonChannelModelExpanded(BaseModel):
    contributions: list[NestedContributionRead] | None = Field(..., title="Contributions")
    created_by: NestedPersonRead
    updated_by: NestedPersonRead
    assets: list[AssetRead] = Field(..., title="Assets")
    type: EntityType | None = None
    authorized_project_id: UUID4 = Field(..., title="Authorized Project Id")
    authorized_public: bool | None = Field(False, title="Authorized Public")
    id: UUID = Field(..., title="Id")
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    description: str = Field(..., title="Description")
    name: str = Field(..., title="Name")
    nmodl_suffix: str = Field(..., title="Nmodl Suffix")
    is_ljp_corrected: bool | None = Field(False, title="Is Ljp Corrected")
    is_temperature_dependent: bool | None = Field(False, title="Is Temperature Dependent")
    temperature_celsius: int = Field(..., title="Temperature Celsius")
    is_stochastic: bool | None = Field(False, title="Is Stochastic")
    neuron_block: NeuronBlock
    species: NestedSpeciesRead
    strain: NestedStrainRead | None = None
    brain_region: BrainRegionRead


class IonChannelModelRead(BaseModel):
    type: EntityType | None = None
    authorized_project_id: UUID4 = Field(..., title="Authorized Project Id")
    authorized_public: bool | None = Field(False, title="Authorized Public")
    id: UUID = Field(..., title="Id")
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    description: str = Field(..., title="Description")
    name: str = Field(..., title="Name")
    nmodl_suffix: str = Field(..., title="Nmodl Suffix")
    is_ljp_corrected: bool | None = Field(False, title="Is Ljp Corrected")
    is_temperature_dependent: bool | None = Field(False, title="Is Temperature Dependent")
    temperature_celsius: int = Field(..., title="Temperature Celsius")
    is_stochastic: bool | None = Field(False, title="Is Stochastic")
    neuron_block: NeuronBlock
    species: NestedSpeciesRead
    strain: NestedStrainRead | None = None
    brain_region: BrainRegionRead


class IonChannelModelWAssets(BaseModel):
    assets: list[AssetRead] = Field(..., title="Assets")
    type: EntityType | None = None
    authorized_project_id: UUID4 = Field(..., title="Authorized Project Id")
    authorized_public: bool | None = Field(False, title="Authorized Public")
    id: UUID = Field(..., title="Id")
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    description: str = Field(..., title="Description")
    name: str = Field(..., title="Name")
    nmodl_suffix: str = Field(..., title="Nmodl Suffix")
    is_ljp_corrected: bool | None = Field(False, title="Is Ljp Corrected")
    is_temperature_dependent: bool | None = Field(False, title="Is Temperature Dependent")
    temperature_celsius: int = Field(..., title="Temperature Celsius")
    is_stochastic: bool | None = Field(False, title="Is Stochastic")
    neuron_block: NeuronBlock
    species: NestedSpeciesRead
    strain: NestedStrainRead | None = None
    brain_region: BrainRegionRead


class ListResponseCircuitRead(BaseModel):
    data: list[CircuitRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class ListResponseElectricalCellRecordingRead(BaseModel):
    data: list[ElectricalCellRecordingRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class ListResponseExperimentalBoutonDensityRead(BaseModel):
    data: list[ExperimentalBoutonDensityRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class ListResponseExperimentalNeuronDensityRead(BaseModel):
    data: list[ExperimentalNeuronDensityRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class ListResponseExperimentalSynapsesPerConnectionRead(BaseModel):
    data: list[ExperimentalSynapsesPerConnectionRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class ListResponseIonChannelModelRead(BaseModel):
    data: list[IonChannelModelRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class ListResponseMEModelCalibrationResultRead(BaseModel):
    data: list[MEModelCalibrationResultRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class ListResponseReconstructionMorphologyRead(BaseModel):
    data: list[ReconstructionMorphologyRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class ListResponseSimulationCampaignRead(BaseModel):
    data: list[SimulationCampaignRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class ListResponseSimulationExecutionRead(BaseModel):
    data: list[SimulationExecutionRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class ListResponseSimulationRead(BaseModel):
    data: list[SimulationRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class ListResponseSimulationResultRead(BaseModel):
    data: list[SimulationResultRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class ListResponseSingleNeuronSimulationRead(BaseModel):
    data: list[SingleNeuronSimulationRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class ListResponseSingleNeuronSynaptomeRead(BaseModel):
    data: list[SingleNeuronSynaptomeRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class ListResponseSingleNeuronSynaptomeSimulationRead(BaseModel):
    data: list[SingleNeuronSynaptomeSimulationRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class MEModelRead(BaseModel):
    contributions: list[NestedContributionRead] | None = Field(..., title="Contributions")
    created_by: NestedPersonRead
    updated_by: NestedPersonRead
    type: EntityType | None = None
    authorized_project_id: UUID4 = Field(..., title="Authorized Project Id")
    authorized_public: bool | None = Field(False, title="Authorized Public")
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    validation_status: ValidationStatus | None = "created"
    id: UUID = Field(..., title="Id")
    species: NestedSpeciesRead
    strain: NestedStrainRead | None = None
    brain_region: BrainRegionRead
    mtypes: list[Annotation] | None = Field(..., title="Mtypes")
    etypes: list[Annotation] | None = Field(..., title="Etypes")
    morphology: ReconstructionMorphologyRead
    emodel: EModelRead
    calibration_result: MEModelCalibrationResultRead | None = None


class MeasurementAnnotationCreate(BaseModel):
    entity_id: UUID = Field(..., title="Entity Id")
    entity_type: MeasurableEntity
    measurement_kinds: list[MeasurementKindCreate] = Field(..., title="Measurement Kinds")


class MeasurementAnnotationRead(BaseModel):
    id: UUID = Field(..., title="Id")
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    entity_id: UUID = Field(..., title="Entity Id")
    entity_type: MeasurableEntity
    measurement_kinds: list[MeasurementKindRead] = Field(..., title="Measurement Kinds")


class ReconstructionMorphologyAnnotationExpandedRead(BaseModel):
    contributions: list[NestedContributionRead] | None = Field(..., title="Contributions")
    created_by: NestedPersonRead
    updated_by: NestedPersonRead
    type: EntityType | None = None
    assets: list[AssetRead] = Field(..., title="Assets")
    authorized_project_id: UUID4 = Field(..., title="Authorized Project Id")
    authorized_public: bool | None = Field(False, title="Authorized Public")
    license: LicenseRead | None = None
    id: UUID = Field(..., title="Id")
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    location: PointLocationBase | None = None
    legacy_id: list[str] | None = Field(..., title="Legacy Id")
    species: NestedSpeciesRead
    strain: NestedStrainRead | None = None
    brain_region: BrainRegionRead
    mtypes: list[Annotation] | None = Field(..., title="Mtypes")
    measurement_annotation: MeasurementAnnotationRead | None = None


class EModelReadExpanded(BaseModel):
    contributions: list[NestedContributionRead] | None = Field(..., title="Contributions")
    created_by: NestedPersonRead
    updated_by: NestedPersonRead
    assets: list[AssetRead] = Field(..., title="Assets")
    type: EntityType | None = None
    authorized_project_id: UUID4 = Field(..., title="Authorized Project Id")
    authorized_public: bool | None = Field(False, title="Authorized Public")
    creation_date: datetime = Field(..., title="Creation Date")
    update_date: datetime = Field(..., title="Update Date")
    description: str = Field(..., title="Description")
    name: str = Field(..., title="Name")
    iteration: str = Field(..., title="Iteration")
    score: float = Field(..., title="Score")
    seed: int = Field(..., title="Seed")
    id: UUID = Field(..., title="Id")
    species: NestedSpeciesRead
    strain: NestedStrainRead | None = None
    brain_region: BrainRegionRead
    mtypes: list[Annotation] | None = Field(..., title="Mtypes")
    etypes: list[Annotation] | None = Field(..., title="Etypes")
    exemplar_morphology: ExemplarMorphology
    ion_channel_models: list[IonChannelModelWAssets] = Field(..., title="Ion Channel Models")


class ListResponseEModelReadExpanded(BaseModel):
    data: list[EModelReadExpanded] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class ListResponseMEModelRead(BaseModel):
    data: list[MEModelRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None


class ListResponseMeasurementAnnotationRead(BaseModel):
    data: list[MeasurementAnnotationRead] = Field(..., title="Data")
    pagination: PaginationResponse
    facets: Facets | None = None
