"""Tests for server schema enum filtering."""

from pathlib import Path

from scripts.filter_server_schema_enums import build_module, extract_enum_class_sources

_SAMPLE = '''\
from pydantic import BaseModel
from entitysdk.compat import StrEnum


class KeepMe(StrEnum):
    a = "a"


class DropMe(BaseModel):
    x: int


class AlsoKeep(StrEnum):
    b = "b"
'''


def test_extract_enum_class_sources() -> None:
    segments = extract_enum_class_sources(_SAMPLE)
    assert len(segments) == 2
    assert "class KeepMe(StrEnum):" in segments[0]
    assert "class AlsoKeep(StrEnum):" in segments[1]


def test_build_module_uses_header() -> None:
    header = "# generated by datamodel-codegen\n\nfrom entitysdk.compat import StrEnum"
    out = build_module(header, extract_enum_class_sources(_SAMPLE))
    assert out.startswith(header)
    assert "DropMe" not in out


def test_filter_script_runs_on_repo_header() -> None:
    repo_root = Path(__file__).resolve().parents[2]
    header = (repo_root / "templates" / "header.jinja2").read_text(encoding="utf-8")
    module = build_module(header, extract_enum_class_sources(_SAMPLE))
    assert "StrEnum" in module
    assert "BaseModel" not in module
