"""Tests for server schema enum filtering."""

from pathlib import Path

from scripts.filter_server_schema_enums import build_module, extract_enum_body

_SAMPLE = """\
from pydantic import BaseModel
from entitysdk.compat import StrEnum


class KeepMe(StrEnum):
    a = "a"


class DropMe(BaseModel):
    x: int


class AlsoKeep(StrEnum):
    b = "b"
"""

_SAMPLE_WITH_GAP = """\
from entitysdk.compat import StrEnum


class First(StrEnum):
    a = "a"


class NotAnEnum:
    pass


class Second(StrEnum):
    b = "b"
"""


def test_extract_enum_body_skips_non_enums() -> None:
    body = extract_enum_body(_SAMPLE)
    assert "class KeepMe(StrEnum):" in body
    assert "class AlsoKeep(StrEnum):" in body
    assert "DropMe" not in body
    assert "class DropMe" not in body


def test_extract_enum_body_ignores_classes_between_enums() -> None:
    body = extract_enum_body(_SAMPLE_WITH_GAP)
    assert "NotAnEnum" not in body
    assert "class First(StrEnum):" in body
    assert "class Second(StrEnum):" in body


def test_build_module_uses_header() -> None:
    header = "# generated by datamodel-codegen\n\nfrom entitysdk.compat import StrEnum"
    out = build_module(header, extract_enum_body(_SAMPLE))
    assert out.startswith(header)
    assert "DropMe" not in out


def test_filter_script_runs_on_repo_header() -> None:
    repo_root = Path(__file__).resolve().parents[2]
    header = (repo_root / "templates" / "header.jinja2").read_text(encoding="utf-8")
    module = build_module(header, extract_enum_body(_SAMPLE))
    assert "StrEnum" in module
    assert "BaseModel" not in module
